#                     #
##  Observer Config  ##
#                     #

ban-cmd: tempban -s %player% 30d Unfair Advantage

punishment-type: none

checks:
  client:
    client:
      a:
        enabled: true
        punishable: true
        experimental: false
        min: 0
        max: 1
        reduce: 0.05
        bufferCeil: 0
        bufferMax: 0
        bufferReduce: 0
        preVlCeil: 0
        preVlMax: 0
        preVlReduce: 0
      b:
        enabled: true
        punishable: true
        experimental: false
        min: 0
        max: 1
        reduce: 0.05
        bufferCeil: 0
        bufferMax: 0
        bufferReduce: 0
        preVlCeil: 0
        preVlMax: 0
        preVlReduce: 0
      c:
        enabled: true
        punishable: true
        experimental: false
        min: 0
        max: 1
        reduce: 0.05
        bufferCeil: 0
        bufferMax: 0
        bufferReduce: 0
        preVlCeil: 0
        preVlMax: 0
        preVlReduce: 0
      d:
        enabled: true
        punishable: true
        experimental: false
        min: 0
        max: 1
        reduce: 0.05
        bufferCeil: 0
        bufferMax: 0
        bufferReduce: 0
        preVlCeil: 0
        preVlMax: 0
        preVlReduce: 0
      e:
        enabled: true
        punishable: true
        experimental: false
        min: 0
        max: 1
        reduce: 0.05
        bufferCeil: 0
        bufferMax: 0
        bufferReduce: 0
        preVlCeil: 0
        preVlMax: 0
        preVlReduce: 0
  movement:
    move:
      enabled: true
      punishable: true
      experimental: true
      min: 0
      max: 10
      reduce: 0.05
      bufferCeil: 0
      bufferMax: 0
      bufferReduce: 0
      preVlCeil: 0
      preVlMax: 0
      preVlReduce: 0
  render:
    chestesp:
      enabled: true
      punishable: false
      experimental: true
      min: 0
      max: 0
      reduce: 0
      bufferCeil: 0
      bufferMax: 0
      bufferReduce: 0
      preVlCeil: 0
      preVlMax: 0
      preVlReduce: 0
      chunkLoad: 8